# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('teacher', models.CharField(max_length=256)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('days_of_week', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(default='12:00')),
                ('end_time', models.TimeField(default='12:00')),
            ],
        ),
    ]
