# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 22:02
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school_class', '0003_schoolclass_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday')], max_length=100),
        ),
    ]
